// Quotes loaded from the local collection
const QUOTES = [
  {"quote":"The secret to your success is found in your daily routine.","author":"John C. Maxwell"},
  {"quote":"The most courageous act is still to think for yourself. Aloud.","author":"Unknown"},
  {"quote":"It's time to start living the life you've only imagined.","author":"Unknown"},
  {"quote":"Do fewer things. Do them better. Know why you're doing them.","author":"Cal Newport"},
  {"quote":"This is the real secret to life—to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.","author":"Alan Watts"},
  {"quote":"Once you replace negative thoughts with positive ones, you'll start having positive results.","author":"Willie Nelson"},
  {"quote":"Be the type of person you want to meet.","author":"Unknown"},
  {"quote":"There is no person living who isn't capable of doing more than they think they can do.","author":"Henry Ford"},
  {"quote":"Live the wonderful life that is in you.","author":"Oscar Wilde"},
  {"quote":"If you can, help others; if you cannot do that, at least do not harm them.","author":"Dalai Lama"},
  {"quote":"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.","author":"Albert Einstein"},
  {"quote":"Life is a series of building, testing, changing and iterating.","author":"Lauren Mosenthal"},
  {"quote":"Your big opportunity may be right where you are now.","author":"Napoleon Hill"},
  {"quote":"No matter the number of times you fail you must be determined to succeed. You must not lose hope. Don't stop in your storm.","author":"Tony Narams"},
  {"quote":"Believe you can and you're halfway there.","author":"Theodore Roosevelt"},
  {"quote":"It doesn't matter who you are, where you come from. The ability to triumph begins with you. Always.","author":"Oprah Winfrey"},
  {"quote":"Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.","author":"Rumi"},
  {"quote":"When something is important enough, you do it even if the odds are not in your favor.","author":"Elon Musk"},
  {"quote":"Breathe. Take care. Stand still for a minute. What you are looking for might just be looking for you too.","author":"Cleo Wade"},
  {"quote":"We are more fulfilled when we are involved in something bigger than ourselves.","author":"John Glenn"},
  {"quote":"If I quit now, I will soon be back to where I started. And when I started I was desperately wishing to be where I am now.","author":"Unknown"},
  {"quote":"If you are not excited about it, it may not be the right path.","author":"Abraham Hicks"},
  {"quote":"Your capacity to say 'No' determines your capacity to say 'Yes' to greater things.","author":"E. Stanley Jones"},
  {"quote":"Go confidently in the direction of your dreams. Live the life you have imagined.","author":"Henry David Thoreau"},
  {"quote":"Where you are is a result of who you were, but where you go depends entirely on who you choose to be.","author":"Hal Elrod"},
  {"quote":"Imagine how you want to feel at the end of the day. Start working towards that now.","author":"Lin-Manuel Miranda"},
  {"quote":"Wherever you are, be all there.","author":"Jim Elliot"},
  {"quote":"Keep moving forward. One step at a time.","author":"Unknown"},
  {"quote":"People may hear your words, but they feel your attitude.","author":"John C. Maxwell"},
  {"quote":"What one has to do usually can be done.","author":"Eleanor Roosevelt"},
  {"quote":"You may not control all the events that happen to you, but you can decide not to be reduced by them.","author":"Maya Angelou"},
  {"quote":"If people aren't laughing at your dreams, your dreams aren't big enough.","author":"Grayson Marshall"},
  {"quote":"Your world is a living expression of how you are using—and have used—your mind.","author":"Earl Nightingale"},
  {"quote":"Don't limit your challenges - challenge your limits.","author":"Unknown"},
  {"quote":"If we are facing in the right direction, all we have to do is keep on walking.","author":"Unknown"},
  {"quote":"You don't have to see the whole staircase. Just take the first step.","author":"Martin Luther King"},
  {"quote":"Everything around you that you call life was made up by people, and you can change it.","author":"Steve Jobs"},
  {"quote":"What gets measured gets managed.","author":"Peter Drucker"},
  {"quote":"Attitude is a little thing that makes a big difference.","author":"Winston Churchill"},
  {"quote":"Most people get ahead during the time that others waste.","author":"Henry Ford"},
  {"quote":"There is no small act of kindness. Every compassionate act makes large the world.","author":"Mary Anne Radmacher"},
  {"quote":"If you spend too much time thinking about a thing, you'll never get it done.","author":"Bruce Lee"},
  {"quote":"If it ain't fun, don't do it.","author":"Jack Canfield"},
  {"quote":"You got this. Make it happen.","author":"Danielle LaPorte"},
  {"quote":"Why fit in when you were born to stand out?","author":"Dr. Seuss"},
  {"quote":"If you don't prioritize your life, someone else will.","author":"Greg McKeown"},
  {"quote":"Anyone who stops learning is old.","author":"Henry Ford"},
  {"quote":"If you tell yourself you can't, you won't.","author":"Dean Graziosi"},
  {"quote":"There is no duty we so much underrate as the duty of being happy. By being happy we sow anonymous benefits upon the world.","author":"Robert Louis Stevenson"},
  {"quote":"Those who can imagine anything can create the impossible.","author":"Alan Turing"},
  {"quote":"It's not what happens to you, but how you react to it that matters.","author":"Epictetus"},
  {"quote":"Your value doesn't decrease based on someone's inability to see your worth.","author":"Unknown"},
  {"quote":"Do not wish for an easy life. Wish for the strength to endure a difficult one.","author":"Bruce Lee"},
  {"quote":"Don't underestimate the value of doing nothing, of just going along, listening to all the things you can't hear, and not bothering.","author":"Winnie the Pooh"},
  {"quote":"If you don't like where you are, change it. You're not a tree.","author":"Jim Rohn"},
  {"quote":"There are always limits, and there are always opportunities. The ones we rehearse and focus on are the ones that shape our attitude and our actions.","author":"Seth Godin"},
  {"quote":"A person is but the product of their thoughts. What they think, they become.","author":"Mahatma Gandhi"},
  {"quote":"Creativity is intelligence having fun.","author":"Albert Einstein"},
  {"quote":"Always do what you are afraid to do.","author":"Ralph Waldo Emerson"},
  {"quote":"Decide whether or not the goal is worth the risks involved. If it is, stop worrying.","author":"Amelia Earhart"},
  {"quote":"Choose your heroes or they will be chosen for you.","author":"Russell Brand"},
  {"quote":"Do what you love, not what you think you're supposed to do.","author":"Unknown"},
  {"quote":"It is never too late to be what you might have been.","author":"Mary Ann Evans"},
  {"quote":"Be thankful for what you have; you'll end up having more. If you concentrate on what you don't have, you will never, ever have enough.","author":"Oprah Winfrey"},
  {"quote":"Be the one who decided to go for it.","author":"Unknown"},
  {"quote":"Continuous effort, not strength or intelligence, is the key to unlocking our potential.","author":"Liane Cordes"},
  {"quote":"We are what we repeatedly do. Excellence then, is not an act, but a habit.","author":"Will Durant"},
  {"quote":"First say to yourself what you would be; and then do what you have to do.","author":"Epictetus"},
  {"quote":"People overestimate what they can do in a single day. And underestimate what they can do in their whole lives.","author":"Unknown"},
  {"quote":"You have to expect things of yourself before you can do them.","author":"Michael Jordan"},
  {"quote":"Do one thing every day that scares you.","author":"Mary Schmich"},
  {"quote":"When I let go of what I am, I become what I might be.","author":"Lao Tzu"},
  {"quote":"Don't blame others as an excuse for you not working hard enough.","author":"Unknown"},
  {"quote":"The brain is like a muscle. When it is in use we feel very good. Understanding is joyous.","author":"Carl Sagan"},
  {"quote":"If you want something you've never had, you must be willing to do something you've never done.","author":"Unknown"},
  {"quote":"Change your life today. Don't gamble on the future, act now, without delay.","author":"Simone de Beauvoir"},
  {"quote":"The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.","author":"Michelangelo"},
  {"quote":"Do more of what makes you happy.","author":"Unknown"},
  {"quote":"What you do today is important because you are exchanging a day of your life for it.","author":"Unknown"},
  {"quote":"Turn your wounds into wisdom.","author":"Oprah Winfrey"},
  {"quote":"If you have good thoughts they will shine out of your face like sunbeams and you will always look lovely.","author":"Roald Dahl"},
  {"quote":"The secret to happiness is freedom. And the secret to freedom is courage.","author":"Thucydides"},
  {"quote":"The creative adult is the child who survived.","author":"Julian F. Fleron"},
  {"quote":"The reason why people give up so fast is because they tend to look at how far they still have to go, instead of how far they have gotten.","author":"Unknown"},
  {"quote":"Yesterday, you said tomorrow.","author":"Nike"},
  {"quote":"Overthinking ruins you. Ruins the situation, twists it around, makes you worry and just makes everything much worse than it actually is.","author":"Unknown"},
  {"quote":"Good judgement comes from experience, and a lot of that comes from bad judgement.","author":"Will Rogers"},
  {"quote":"The first step to accepting yourself is to stop comparing yourself to others.","author":"Joe Duncan"},
  {"quote":"Success is the ability to go from failure to failure without losing your enthusiasm.","author":"Winston Churchill"},
  {"quote":"Don't let yesterday use up too much of today.","author":"Will Rogers"},
  {"quote":"Always remember that the future comes one day at a time.","author":"Dean Acheson"},
  {"quote":"Believe in yourself.","author":"Unknown"},
  {"quote":"Success is something you attract by the person you become.","author":"Jim Rohn"},
  {"quote":"The primary cause of unhappiness is never the situation but your thoughts about it.","author":"Eckhart Tolle"},
  {"quote":"Happiness is not the absence of problems, it's the ability to deal with them.","author":"Unknown"},
  {"quote":"Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.","author":"Mary Lou Retton"},
  {"quote":"Impossible is just a big word thrown around by small men and women who find it easier to live in the world they've been given than to explore the power they have to change it.","author":"Muhammad Ali"},
  {"quote":"The wisest mind has something yet to learn.","author":"George Santayana"},
  {"quote":"Whatever you're meant to do, do it now. The conditions are always impossible.","author":"Doris Lessing"},
  {"quote":"The cave you fear to enter holds the treasure that you seek.","author":"Joseph Campbell"},
  {"quote":"No matter what people tell you, words and ideas can change the world.","author":"Robin Williams"},
  {"quote":"The cure to boredom is curiosity. There is no cure for curiosity.","author":"Dorothy Parker"},
  {"quote":"What are the most powerful words in the universe? The ones you use to talk to yourself.","author":"Karen Salmansohn"},
  {"quote":"Failure is simply the opportunity to begin again, this time more intelligently.","author":"Henry Ford"},
  {"quote":"On your journey through life, make sure your biography has at least one extraordinary chapter.","author":"Unknown"},
  {"quote":"Winning starts with beginning.","author":"Unknown"},
  {"quote":"I would rather die of passion than of boredom.","author":"Vincent Van Gogh"},
  {"quote":"Be kind; everyone you meet is fighting a hard battle.","author":"Ian Maclaren"},
  {"quote":"Let go of those who bring you down and surround yourself with those who bring out the best in you.","author":"Unknown"},
  {"quote":"Do small things with great love.","author":"Mother Teresa"},
  {"quote":"Every person is a new door to a different world.","author":"Six Degrees of Separation"},
  {"quote":"Do more with less.","author":"Unknown"},
  {"quote":"The only way of finding the limits of the possible is by going beyond them into the impossible.","author":"Arthur C. Clarke"},
  {"quote":"Our attitude toward life determines life's attitude towards us.","author":"Earl Nightingale"},
  {"quote":"Soon is not as good as now.","author":"Seth Godin"},
  {"quote":"You can be happy or you can be unhappy. It's just according to the way you look at things.","author":"Walt Disney"},
  {"quote":"Change your thoughts and you change your world.","author":"Norman Vincent Peale"},
  {"quote":"Everything that irritates us about others can lead us to an understanding of ourselves.","author":"Carl Jung"},
  {"quote":"It is more important to know where you are going than to get there quickly. Do not mistake activity for achievement.","author":"Isocrates"},
  {"quote":"May your choices reflect your hopes, not your fears.","author":"Nelson Mandela"},
  {"quote":"If you listen to your fears, you will die never knowing what a great person you might have been.","author":"Robert Schuller"},
  {"quote":"If you find yourself constantly trying to prove your worth to someone, you have already forgotten your value.","author":"Unknown"},
  {"quote":"Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements.","author":"Napoleon Hill"},
  {"quote":"The death of a dream is the day that you stop believing in the work it takes to get there.","author":"Chris Burkmenn"},
  {"quote":"Don't let someone who gave up on their dreams talk you out of going after yours.","author":"Zig Ziglar"},
  {"quote":"Simplicity is the ultimate sophistication.","author":"Leonardo da Vinci"},
  {"quote":"Sometimes life hits you in the head with a brick. Don't lose faith.","author":"Steve Jobs"},
  {"quote":"Don't regret anything you do, because in the end it makes you who you are.","author":"Unknown"},
  {"quote":"The secret of change is to focus all of your energy, not on fighting the old but on building the new.","author":"Dan Millman"}
];
